# Generated by Django 6.1 on 2026-09-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_conversation_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_agent_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_customer_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
