# Generated by Django 6.1 on 2026-09-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_conversation_is_agent_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_admin_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
