# Generated by Django 6.1 on 2026-09-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_name_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'Support Agent'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='customer', max_length=20),
        ),
    ]
